#!/bin/sh

set -e

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] ; then
    update-alternatives --install /usr/bin/jolicloud-webapps-engine \
        jolicloud-webapps-engine /usr/bin/nickel-browser 60
fi